---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: cross-node-cluster-3
network.host: 0.0.0.0
node.roles: [ master, data, ingest, remote_cluster_client ]
## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: trial
xpack.security.enabled: true

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.client_authentication: required
xpack.security.transport.ssl.verification_mode: none
xpack.security.transport.ssl.key: "${CONFIG_DIR}/certs/elasticsearch/elasticsearch-3.key"
xpack.security.transport.ssl.certificate: "${CONFIG_DIR}/certs/elasticsearch/elasticsearch-3.crt"
xpack.security.transport.ssl.certificate_authorities: "${CONFIG_DIR}/certs/ca/ca.crt"

xpack.security.remote_cluster_server.ssl.client_authentication: required
xpack.security.remote_cluster_server.ssl.enabled: true
xpack.security.remote_cluster_server.ssl.certificate: "${CONFIG_DIR}/certs/elasticsearch/elasticsearch-3.crt"
xpack.security.remote_cluster_server.ssl.key: "${CONFIG_DIR}/certs/elasticsearch/elasticsearch-3.key"
xpack.security.remote_cluster_server.ssl.certificate_authorities: "${CONFIG_DIR}/certs/ca/ca.crt"

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: "${CONFIG_DIR}/certs/elasticsearch/elasticsearch-3.key"
xpack.security.http.ssl.certificate: "${CONFIG_DIR}/certs/elasticsearch/elasticsearch-3.crt"
xpack.security.http.ssl.certificate_authorities: "${CONFIG_DIR}/certs/ca/ca.crt"