version: '3.7'

networks:
  elastic-singlenode:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
services:
  setup:
    profiles:
      - setup
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      elastic-singlenode: 
        ipv4_address: 10.5.0.4
    depends_on:
      - elasticsearch
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    networks:
      elastic-singlenode:
        ipv4_address: 10.5.0.2
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: "curl -s http://elasticsearch:9200/_cluster/health?pretty -u elastic:${ELASTIC_PASSWORD:-} | grep status | grep -q '\\(green\\|yellow\\)'"
      interval: 10s
      retries: 10
      start_period: 10s

  kibana:
    networks:
      elastic-singlenode:
        ipv4_address: 10.5.0.3
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    volumes:
      - ./config/kibana.yaml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    healthcheck:
      test: "curl -s http://127.0.0.1:5601/api/status -u elastic:changeme | grep status | grep '{\"overall\":{\"level\":\"available\"'"
      interval: 10s
      retries: 20
      start_period: 10s
    depends_on:
      - elasticsearch
  init-data:
    build: .
    image: alpine:3.12
    container_name: data
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    volumes:
      - ./config/demo-data:/demo-data
    entrypoint: /bin/sh -c /demo-data/entrypoint.sh
    networks: 
      elastic-singlenode: 
        ipv4_address: 10.5.0.5
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy


volumes:
  elasticsearch-data:
    driver: local